wandb_version: 1

database:
  desc: null
  value: moving_mnist
batch_size:
  desc: null
  value: 200
epochs:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715253185
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
