wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716139233
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.17.0
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.01
