batch_size: 32

# Sequence
channels: 3
image_size: 128
patch_size: 16
seq_length: 10

rollout_times: 2

save_path: 
  reconstruct: '../data/rec/'
  checkpoint: '../data/ckpt/'

dataset: 
  train: '../dataset_split/csv/train_file.csv'
  valid: '../dataset_split/csv/valid_file.csv'
  # test: '../dataset_split/csv/test_file.csv'