batch_size: 50 #A100 128

# Sequence
channels: 3
image_size: 128
patch_size: 16
seq_length: 10

simulation: 


train:
  dataset: '../dataset_split/csv/train_file.csv'
  loss_fn: "MSE"
  rollout_times: 2
  save_checkpoint: '../data/ckpt/'
  save_loss: '../data/loss/'


valid: 
  dataset: '../dataset_split/csv/valid_file.csv'
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"
  save_reconstruct: '../data/rec/'
  save_loss: '../data/loss/'
  
test:
  dataset: 
    - inner100
    - outer100
    - inner200
    - outer200
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"
  
  

