wandb_version: 1

database:
  desc: null
  value: shallow_water
batch_size:
  desc: null
  value: 50
epochs:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715251375.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
