database: shallow_water
image_size: 128
channels: 3

batch_size: 25 #A100 128
patch_size: 16
seq_length: 10
mask_method: "zeros"
save_loss: '../data/shallow_water/imae/loss/'

imae: 
  num_layers: 6
  nhead: 6

convlstm:
  hidden_dim: [64, 64, 128]
  kernel_size: [3, 3]
  num_layers: 3

caelstm:
  cae_hidden_dim: 256
  lstm_hidden_dim: 256

train:
  loss_fn: "MSE"
  optimizer: "AdamW"
  scheduler: "CosineAnnealingLR"
  learning_rate: 0.0001
  rollout_times: 2
  save_checkpoint: '../data/shallow_water/imae/ckpt/'
  


valid: 
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"
  save_reconstruct: '../data/shallow_water/imae/rec/'
  
test:
  dataset: 
    - inner100
    - outer100
    - inner200
    - outer200
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"