database: moving_mnist
image_size: 64
channels: 1

batch_size: 128
patch_size: 8
seq_length: 5
mask_method: "random"
save_loss: '/home/uceckz0/Project/imae/data/moving_mnist/imae/loss/'

model: 
  num_layers: 5
  nhead: 8

train:
  loss_fn: "BCE"
  optimizer: "RMSprop"
  scheduler: "StepLR"
  learning_rate: 0.0001
  rollout_times: 2
  save_checkpoint: '../data/moving_mnist/imae/ckpt/'
  


valid: 
  rollout_times: 2
  metric: 
    - "BCE"
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"
  save_reconstruct: '../data/moving_mnist/imae/rec/'
  
test:
  dataset: 
    - inner100
    - outer100
    - inner200
    - outer200
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"