database: shallow_water
image_size: 128
channels: 3

batch_size: 32 #A100 128
patch_size: 16
seq_length: 10
mask_method: "zeros"


imae: 
  num_layers: 6
  nhead: 6
  save_loss: '../data/shallow_water/imae/loss/'
  save_checkpoint: '../data/shallow_water/imae/ckpt/'
  save_reconstruct: '../data/shallow_water/imae/rec/'


convlstm:
  hidden_dim: [32, 32]
  kernel_size: [3, 3]
  num_layers: 2
  save_loss: '../data/shallow_water/convlstm/loss/'
  save_checkpoint: '../data/shallow_water/convlstm/ckpt/'
  save_reconstruct: '../data/shallow_water/convlstm/rec/'

cae:
  latent_dim: 128
  save_loss: '../data/shallow_water/cae/loss/'
  save_checkpoint: '../data/shallow_water/cae/ckpt/'
  save_reconstruct: '../data/shallow_water/cae/rec/'

caelstm: 
  hidden_dim: 1280
  save_loss: '../data/shallow_water/caelstm/loss/'
  save_checkpoint: '../data/shallow_water/caelstm/ckpt/'
  save_reconstruct: '../data/shallow_water/caelstm/rec/'


train:
  loss_fn: "MSE"
  optimizer: "AdamW"
  scheduler: "CosineAnnealingLR"
  learning_rate: 0.0001
  rollout_times: 2
 

valid: 
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"
  
  
test:
  dataset: 
    - inner100
    - outer100
    - inner200
    - outer200
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"