batch_size: 320

# Sequence
patch_size: 8
seq_length: 5

model: 
  num_layers: 5
  nhead: 16

train:
  loss_fn: "BCE"
  optimizer: "RMSprop"
  learning_rate: 0.001
  rollout_times: 2
  save_checkpoint: '../data/moving_mnist/ckpt/'
  save_loss: '../data/moving_mnist/loss/'


valid: 
  rollout_times: 2
  metric: 
    - "BCE"
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"
  save_reconstruct: '../data/moving_mnist/rec/'
  save_loss: '../data/moving_mnist/loss/'
  
test:
  dataset: 
    - inner100
    - outer100
    - inner200
    - outer200
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"
  
  

