batch_size: 50 #A100 128

patch_size: 16
seq_length: 10

model: 
  num_layers: 6
  nhead: 6

train:
  loss_fn: "MSE"
  optimizer: "AdamW"
  learning_rate: 0.0001
  rollout_times: 2
  save_checkpoint: '../data/shallow_water/ckpt/'
  save_loss: '../data/shallow_water/loss/'


valid: 
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"
  save_reconstruct: '../data/shallow_water/rec/'
  save_loss: '../data/shallow_water/loss/'
  
test:
  dataset: 
    - inner100
    - outer100
    - inner200
    - outer200
  rollout_times: 2
  metric: 
    - "MSE"
    - "RMSE"
    - "MAE" 
    - "SSIM" 
    - "PSNR"
  
  

