method: "random"
metric:
  goal: "minimize"
  name: "score"
parameters:
  patch_size:
    values:
      - 4
      - 8
      - 16
  num_layers: 
    values:
      - 4
      - 5
      - 6
      - 7
      - 8
  optimizer: 
    values:
      - 0
      - 1
  learning_rate: 
    max: 0.01
    min: 0.0001